import { EDITORIAL_USER_ID, type Look, type ProductOffer, type ProductTag } from "./types";

const EUR = "EUR";

function offer(
  id: string,
  retailerId: string,
  price: string,
  url: string,
): ProductOffer {
  return { id, retailerId, price, currency: EUR, url };
}

function tag(
  base: Omit<ProductTag, "currency" | "offers"> & {
    offers: ProductOffer[];
    wornUrl: string;
    wornRetailerId: string;
  },
): ProductTag {
  const priced = base.offers.filter((item) => Number.parseFloat(item.price) > 0);
  const lowest = priced.reduce(
    (best, item) => (Number.parseFloat(item.price) < Number.parseFloat(best.price) ? item : best),
    priced[0] ?? base.offers[0],
  );
  return {
    ...base,
    currency: EUR,
    url: lowest?.url ?? base.url,
    price: lowest?.price ?? "",
    retailerId: lowest?.retailerId ?? base.wornRetailerId,
    offers: base.offers,
    wornUrl: base.wornUrl,
    wornRetailerId: base.wornRetailerId,
  };
}

function worn(
  id: string,
  x: number,
  y: number,
  name: string,
  brand: string,
  price: string,
  url: string,
  retailerId: string,
): ProductTag {
  return tag({
    id,
    x,
    y,
    name,
    brand,
    price,
    url,
    retailerId,
    wornUrl: url,
    wornRetailerId: retailerId,
    offers: [offer(`${id}-live`, retailerId, price, url)],
  });
}

const RAW_SEED: Array<Omit<Look, "userId">> = [
  {
    id: "seed-sunday-coat",
    title: "Sunday Coat",
    caption: "Camel wool, cream knit, one bag that does the whole day.",
    creator: "Maya Chen",
    moods: ["tailored"],
    imageSrc: "/looks/sunday-coat.jpg",
    createdAt: Date.parse("2026-08-12T10:00:00Z"),
    updatedAt: Date.parse("2026-08-12T10:00:00Z"),
    tags: [
      tag({
        id: "sc-coat",
        x: 48,
        y: 38,
        name: "Oversized Wool Coat",
        brand: "COS",
        price: "160",
        url: "https://www.zalando.de/weekday-oversized-classic-coat-dark-brown-web21u048-o11.html",
        retailerId: "zalando",
        wornUrl:
          "https://www.cos.com/en-de/women/womenswear/coatsjackets/coats/product/oversized-double-breasted-wool-coat-dark-green-1298577001",
        wornRetailerId: "cos",
        offers: [
          offer(
            "sc-coat-zal",
            "zalando",
            "160",
            "https://www.zalando.de/weekday-oversized-classic-coat-dark-brown-web21u048-o11.html",
          ),
          offer(
            "sc-coat-cos",
            "cos",
            "279",
            "https://www.cos.com/en-de/women/womenswear/coatsjackets/coats/product/oversized-double-breasted-wool-coat-dark-green-1298577001",
          ),
        ],
      }),
      tag({
        id: "sc-knit",
        x: 50,
        y: 26,
        name: "Cashmere Turtleneck",
        brand: "Uniqlo",
        price: "99.90",
        url: "https://www.uniqlo.com/de/en/products/E450637-000/00",
        retailerId: "uniqlo",
        wornUrl: "https://www.uniqlo.com/de/en/products/E450637-000/00",
        wornRetailerId: "uniqlo",
        offers: [
          offer(
            "sc-knit-uq",
            "uniqlo",
            "99.90",
            "https://www.uniqlo.com/de/en/products/E450637-000/00",
          ),
          offer(
            "sc-knit-zal",
            "zalando",
            "183.95",
            "https://www.zalando.de/pure-cashmere-turtleneck-loosefit-jumper-pug21i004-c11.html",
          ),
        ],
      }),
      worn(
        "sc-tote",
        74,
        52,
        "Kley Tote",
        "Sézane",
        "335",
        "https://www.sezane.com/de-en/product/octobre-editions/kley-tote-bag/camel-suede",
        "sezane",
      ),
      worn(
        "sc-boots",
        48,
        88,
        "Block-Heel Leather Boots",
        "NEWD.",
        "179.80",
        "https://www.zalando.de/newdtamaris-stiefel-cognac-n5511a00t-o11.html",
        "zalando",
      ),
    ],
  },
  {
    id: "seed-gallery-hour",
    title: "Gallery Hour",
    caption: "Bias satin and a quiet clutch — dressed, not decorated.",
    creator: "Elise Moreau",
    moods: ["evening"],
    imageSrc: "/looks/gallery-hour.jpg",
    createdAt: Date.parse("2026-08-18T18:30:00Z"),
    updatedAt: Date.parse("2026-08-18T18:30:00Z"),
    tags: [
      worn(
        "gh-dress",
        50,
        42,
        "SARA Satin Dress",
        "Maisonêtre",
        "125.95",
        "https://www.zalando.de/maisonetre-sara-dress-cocktailkleidfestliches-kleid-burgundy-08f21c00h-g11.html",
        "zalando",
      ),
      worn(
        "gh-clutch",
        70,
        55,
        "Gabin Bag",
        "Sézane",
        "420",
        "https://www.sezane.com/de-en/product/gabin-bag/taupe",
        "sezane",
      ),
      worn(
        "gh-heels",
        50,
        91,
        "Leather Knee Boots",
        "Moschino",
        "612",
        "https://www.zalando.de/moschino-stiefel-blackcognac-6mo12k010-q11.html",
        "zalando",
      ),
      worn(
        "gh-ear",
        50,
        14,
        "Hoop Earrings Set",
        "& Other Stories",
        "45",
        "https://www.stories.com/en-de/product/hoop-earrings-set-gold-1304803001/",
        "stories",
      ),
    ],
  },
  {
    id: "seed-city-cut",
    title: "City Cut",
    caption: "A blazer that behaves like a coat, jeans that stay sharp.",
    creator: "Noor Alavi",
    moods: ["tailored"],
    imageSrc: "/looks/city-cut.jpg",
    createdAt: Date.parse("2026-08-22T14:00:00Z"),
    updatedAt: Date.parse("2026-08-22T14:00:00Z"),
    tags: [
      worn(
        "cc-blazer",
        50,
        32,
        "Oversized Wool Blazer",
        "COS",
        "195",
        "https://www.cos.com/en-de/women/womenswear/coatsjackets/blazers/product/oversized-pinstriped-wool-blazer-navy-pinstriped-1169204002",
        "cos",
      ),
      worn(
        "cc-tank",
        50,
        24,
        "Ribbed Cotton Tank",
        "H&M",
        "12.99",
        "https://www2.hm.com/de_de/productpage.1318958001.html",
        "hm",
      ),
      worn(
        "cc-jeans",
        50,
        62,
        "Barrel-Leg Jeans",
        "ARKET",
        "119",
        "https://www.arket.com/en-de/product/barrel-leg-jeans-washed-blue-1275390003/",
        "arket",
      ),
      worn(
        "cc-loafers",
        48,
        90,
        "Leather Loafers",
        "Massimo Dutti",
        "89.95",
        "https://www.massimodutti.com/de/lederloafer-mit-profilsohle-l12520750",
        "massimodutti",
      ),
    ],
  },
  {
    id: "seed-studio-knit",
    title: "Studio Knit",
    caption: "Oatmeal rib, chocolate leather, boots that mean it.",
    creator: "Sienna Park",
    moods: ["knit"],
    imageSrc: "/looks/studio-knit.jpg",
    createdAt: Date.parse("2026-08-26T11:00:00Z"),
    updatedAt: Date.parse("2026-08-26T11:00:00Z"),
    tags: [
      worn(
        "sk-knit",
        50,
        28,
        "Merino Turtleneck",
        "COS",
        "89",
        "https://www.cos.com/en-de/women/womenswear/knitwear/jumpers/merino/product/merino-wool-turtleneck-jumper-dark-red-mlange-1232810006",
        "cos",
      ),
      worn(
        "sk-skirt",
        50,
        50,
        "Box-Pleat Midi Skirt",
        "Massimo Dutti",
        "80",
        "https://www.zalando.de/massimo-dutti-a-linien-rock-black-m3i21b0uz-q11.html",
        "zalando",
      ),
      worn(
        "sk-boots",
        48,
        80,
        "Knee-High Leather Boots",
        "Moschino",
        "612",
        "https://www.zalando.de/moschino-stiefel-blackcognac-6mo12k010-q11.html",
        "zalando",
      ),
      worn(
        "sk-hoops",
        38,
        16,
        "Droplet Hoops",
        "& Other Stories",
        "25",
        "https://www.stories.com/en-de/product/droplet-hoop-earrings-gold-1248730001/",
        "stories",
      ),
    ],
  },
  {
    id: "seed-quiet-tailor",
    title: "Quiet Tailor",
    caption: "Knit polo, pleats, a coat carried rather than worn.",
    creator: "Jonah Hale",
    moods: ["tailored"],
    imageSrc: "/looks/quiet-tailor.jpg",
    createdAt: Date.parse("2026-08-29T09:30:00Z"),
    updatedAt: Date.parse("2026-08-29T09:30:00Z"),
    tags: [
      worn(
        "qt-polo",
        50,
        32,
        "Merino Mock-Neck",
        "COS",
        "69",
        "https://www.cos.com/en-de/men/menswear/knitwear/jumpers/merino/product/slim-merino-wool-mock-neck-jumper-black-1261867004",
        "cos",
      ),
      worn(
        "qt-trousers",
        50,
        60,
        "Pleated Wide-Leg Trousers",
        "COS",
        "149",
        "https://www.cos.com/en-de/men/menswear/trousers/relaxed-fit/wideleg/product/wide-leg-pleated-wool-trousers-relaxed-black-1242415001",
        "cos",
      ),
      worn(
        "qt-loafers",
        48,
        90,
        "Suede Derbies",
        "Tommy Hilfiger",
        "118.95",
        "https://www.zalando.de/tommy-hilfiger-stitchdown-sportlicher-schnuerer-coconut-grove-to112c066-o11.html",
        "zalando",
      ),
      worn(
        "qt-coat",
        76,
        48,
        "Wool Overcoat",
        "HUGO",
        "449.95",
        "https://www.zalando.de/hugo-menci-klassischer-mantel-black-hu722t0ri-q11.html",
        "zalando",
      ),
      worn(
        "qt-belt",
        50,
        45,
        "Leather Belt",
        "Massimo Dutti",
        "50",
        "https://www.massimodutti.com/de/gurtel-aus-leder-mit-quadratischer-schnalle-l06189694",
        "massimodutti",
      ),
    ],
  },
  {
    id: "seed-coastal-linen",
    title: "Coastal Linen",
    caption: "A white shirt, khaki shorts, and a bag that holds the afternoon.",
    creator: "Lila Voss",
    moods: ["coastal"],
    imageSrc: "/looks/coastal-linen.jpg",
    createdAt: Date.parse("2026-09-01T16:00:00Z"),
    updatedAt: Date.parse("2026-09-01T16:00:00Z"),
    tags: [
      tag({
        id: "cl-shirt",
        x: 48,
        y: 32,
        name: "Linen Shirt",
        brand: "Zara",
        price: "30.99",
        url: "https://www.zalando.de/pier-one-shirt-mottled-light-green-pi922d0b1-m11.html",
        retailerId: "zalando",
        wornUrl: "https://www.zara.com/de/en/regular-fit-100-linen-shirt-p03090110.html",
        wornRetailerId: "zara",
        offers: [
          offer(
            "cl-shirt-pier",
            "zalando",
            "30.99",
            "https://www.zalando.de/pier-one-shirt-mottled-light-green-pi922d0b1-m11.html",
          ),
          offer(
            "cl-shirt-zara",
            "zara",
            "45.95",
            "https://www.zara.com/de/en/regular-fit-100-linen-shirt-p03090110.html",
          ),
          offer(
            "cl-shirt-arket",
            "zalando",
            "69",
            "https://www.zalando.de/arket-shirt-off-white-aru22d02f-a11.html",
          ),
        ],
      }),
      worn(
        "cl-shorts",
        48,
        52,
        "Linen Bermuda Shorts",
        "Mango",
        "45.99",
        "https://shop.mango.com/de/en/p/men/shorts/linen-blend-bermuda-shorts/100-linen-bermuda-shorts_37071334",
        "mango",
      ),
      worn(
        "cl-shoes",
        48,
        90,
        "Woven Espadrilles",
        "Anna Field",
        "29.99",
        "https://www.zalando.de/anna-field-keilsandalette-cognac-an611a0yq-o11.html",
        "zalando",
      ),
      worn(
        "cl-tote",
        70,
        48,
        "Leather Tote",
        "Zara",
        "139",
        "https://www.zara.com/de/en/leather-shopper-bag-p16167810.html",
        "zara",
      ),
    ],
  },
];

export const SEED_LOOKS: Look[] = RAW_SEED.map((look) => ({
  ...look,
  userId: EDITORIAL_USER_ID,
}));
