/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DesignRouteImport } from './routes/design'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RankRouteImport } from './routes/rank'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminHousesRouteImport } from './routes/admin_.houses'
import { Route as AdminLookRouteImport } from './routes/admin_.look'
import { Route as AdminObservabilityRouteImport } from './routes/admin_.observability'
import { Route as AdminShopsRouteImport } from './routes/admin_.shops'
import { Route as AdminStudioRouteImport } from './routes/admin_.studio'
import { Route as CreatorsUserIdRouteImport } from './routes/creators.$userId'
import { Route as HousesLabelIdRouteImport } from './routes/houses_.$labelId'
import { Route as HousesApplyRouteImport } from './routes/houses_.apply'
import { Route as LooksLookIdRouteImport } from './routes/looks.$lookId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HousesLabelIdCollectionIdRouteImport } from './routes/houses_.$labelId_.$collectionId'
import { Route as LooksLookIdEditRouteImport } from './routes/looks.$lookId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RankRoute = RankRouteImport.update({
  id: '/rank',
  path: '/rank',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHousesRoute = AdminHousesRouteImport.update({
  id: '/admin_/houses',
  path: '/admin/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLookRoute = AdminLookRouteImport.update({
  id: '/admin_/look',
  path: '/admin/look',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminObservabilityRoute = AdminObservabilityRouteImport.update({
  id: '/admin_/observability',
  path: '/admin/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/admin_/shops',
  path: '/admin/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudioRoute = AdminStudioRouteImport.update({
  id: '/admin_/studio',
  path: '/admin/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsUserIdRoute = CreatorsUserIdRouteImport.update({
  id: '/creators/$userId',
  path: '/creators/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesLabelIdRoute = HousesLabelIdRouteImport.update({
  id: '/houses_/$labelId',
  path: '/houses/$labelId',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesApplyRoute = HousesApplyRouteImport.update({
  id: '/houses_/apply',
  path: '/houses/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksLookIdRoute = LooksLookIdRouteImport.update({
  id: '/looks/$lookId',
  path: '/looks/$lookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesLabelIdCollectionIdRoute =
  HousesLabelIdCollectionIdRouteImport.update({
    id: '/houses_/$labelId_/$collectionId',
    path: '/houses/$labelId/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LooksLookIdEditRoute = LooksLookIdEditRouteImport.update({
  id: '/looks/$lookId_/edit',
  path: '/looks/$lookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/design': typeof DesignRoute
  '/houses': typeof HousesRoute
  '/login': typeof LoginRoute
  '/rank': typeof RankRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/houses': typeof AdminHousesRoute
  '/admin/look': typeof AdminLookRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/creators/$userId': typeof CreatorsUserIdRoute
  '/houses/$labelId': typeof HousesLabelIdRoute
  '/houses/apply': typeof HousesApplyRoute
  '/looks/$lookId': typeof LooksLookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/houses/$labelId/$collectionId': typeof HousesLabelIdCollectionIdRoute
  '/looks/$lookId/edit': typeof LooksLookIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/design': typeof DesignRoute
  '/houses': typeof HousesRoute
  '/login': typeof LoginRoute
  '/rank': typeof RankRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/houses': typeof AdminHousesRoute
  '/admin/look': typeof AdminLookRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/studio': typeof AdminStudioRoute
  '/creators/$userId': typeof CreatorsUserIdRoute
  '/houses/$labelId': typeof HousesLabelIdRoute
  '/houses/apply': typeof HousesApplyRoute
  '/looks/$lookId': typeof LooksLookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/houses/$labelId/$collectionId': typeof HousesLabelIdCollectionIdRoute
  '/looks/$lookId/edit': typeof LooksLookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create': typeof CreateRoute
  '/design': typeof DesignRoute
  '/houses': typeof HousesRoute
  '/login': typeof LoginRoute
  '/rank': typeof RankRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin_/houses': typeof AdminHousesRoute
  '/admin_/look': typeof AdminLookRoute
  '/admin_/observability': typeof AdminObservabilityRoute
  '/admin_/shops': typeof AdminShopsRoute
  '/admin_/studio': typeof AdminStudioRoute
  '/creators/$userId': typeof CreatorsUserIdRoute
  '/houses_/$labelId': typeof HousesLabelIdRoute
  '/houses_/apply': typeof HousesApplyRoute
  '/looks/$lookId': typeof LooksLookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/houses_/$labelId_/$collectionId': typeof HousesLabelIdCollectionIdRoute
  '/looks/$lookId_/edit': typeof LooksLookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create'
    | '/design'
    | '/houses'
    | '/login'
    | '/rank'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/houses'
    | '/admin/look'
    | '/admin/observability'
    | '/admin/shops'
    | '/admin/studio'
    | '/creators/$userId'
    | '/houses/$labelId'
    | '/houses/apply'
    | '/looks/$lookId'
    | '/api/auth/$'
    | '/houses/$labelId/$collectionId'
    | '/looks/$lookId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/create'
    | '/design'
    | '/houses'
    | '/login'
    | '/rank'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/houses'
    | '/admin/look'
    | '/admin/observability'
    | '/admin/shops'
    | '/admin/studio'
    | '/creators/$userId'
    | '/houses/$labelId'
    | '/houses/apply'
    | '/looks/$lookId'
    | '/api/auth/$'
    | '/houses/$labelId/$collectionId'
    | '/looks/$lookId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/create'
    | '/design'
    | '/houses'
    | '/login'
    | '/rank'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin_/houses'
    | '/admin_/look'
    | '/admin_/observability'
    | '/admin_/shops'
    | '/admin_/studio'
    | '/creators/$userId'
    | '/houses_/$labelId'
    | '/houses_/apply'
    | '/looks/$lookId'
    | '/api/auth/$'
    | '/houses_/$labelId_/$collectionId'
    | '/looks/$lookId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreateRoute: typeof CreateRoute
  DesignRoute: typeof DesignRoute
  HousesRoute: typeof HousesRoute
  LoginRoute: typeof LoginRoute
  RankRoute: typeof RankRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminHousesRoute: typeof AdminHousesRoute
  AdminLookRoute: typeof AdminLookRoute
  AdminObservabilityRoute: typeof AdminObservabilityRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminStudioRoute: typeof AdminStudioRoute
  CreatorsUserIdRoute: typeof CreatorsUserIdRoute
  HousesLabelIdRoute: typeof HousesLabelIdRoute
  HousesApplyRoute: typeof HousesApplyRoute
  LooksLookIdRoute: typeof LooksLookIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  HousesLabelIdCollectionIdRoute: typeof HousesLabelIdCollectionIdRoute
  LooksLookIdEditRoute: typeof LooksLookIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank': {
      id: '/rank'
      path: '/rank'
      fullPath: '/rank'
      preLoaderRoute: typeof RankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/houses': {
      id: '/admin_/houses'
      path: '/admin/houses'
      fullPath: '/admin/houses'
      preLoaderRoute: typeof AdminHousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/look': {
      id: '/admin_/look'
      path: '/admin/look'
      fullPath: '/admin/look'
      preLoaderRoute: typeof AdminLookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/observability': {
      id: '/admin_/observability'
      path: '/admin/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AdminObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/shops': {
      id: '/admin_/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/studio': {
      id: '/admin_/studio'
      path: '/admin/studio'
      fullPath: '/admin/studio'
      preLoaderRoute: typeof AdminStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators/$userId': {
      id: '/creators/$userId'
      path: '/creators/$userId'
      fullPath: '/creators/$userId'
      preLoaderRoute: typeof CreatorsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses_/$labelId': {
      id: '/houses_/$labelId'
      path: '/houses/$labelId'
      fullPath: '/houses/$labelId'
      preLoaderRoute: typeof HousesLabelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses_/apply': {
      id: '/houses_/apply'
      path: '/houses/apply'
      fullPath: '/houses/apply'
      preLoaderRoute: typeof HousesApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks/$lookId': {
      id: '/looks/$lookId'
      path: '/looks/$lookId'
      fullPath: '/looks/$lookId'
      preLoaderRoute: typeof LooksLookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses_/$labelId_/$collectionId': {
      id: '/houses_/$labelId_/$collectionId'
      path: '/houses/$labelId/$collectionId'
      fullPath: '/houses/$labelId/$collectionId'
      preLoaderRoute: typeof HousesLabelIdCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks/$lookId_/edit': {
      id: '/looks/$lookId_/edit'
      path: '/looks/$lookId/edit'
      fullPath: '/looks/$lookId/edit'
      preLoaderRoute: typeof LooksLookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreateRoute: CreateRoute,
  DesignRoute: DesignRoute,
  HousesRoute: HousesRoute,
  LoginRoute: LoginRoute,
  RankRoute: RankRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminHousesRoute: AdminHousesRoute,
  AdminLookRoute: AdminLookRoute,
  AdminObservabilityRoute: AdminObservabilityRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminStudioRoute: AdminStudioRoute,
  CreatorsUserIdRoute: CreatorsUserIdRoute,
  HousesLabelIdRoute: HousesLabelIdRoute,
  HousesApplyRoute: HousesApplyRoute,
  LooksLookIdRoute: LooksLookIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  HousesLabelIdCollectionIdRoute: HousesLabelIdCollectionIdRoute,
  LooksLookIdEditRoute: LooksLookIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
